import type { Person } from "@/types/person";

const BASE = "/personas";

export const MOCK_PERSONS: Person[] = [
  {
    id: "seed-01",
    name: "Dayany y Dayerlin Sánchez",
    age: 40,
    gender: "F",
    last_location: "Venezuela (ubicación exacta desconocida)",
    latitude: 10.6,
    longitude: -66.93,
    description: "No se sabe de ellas después del terremoto del 24 de junio. C.I. 16129448 / 1612450.",
    cedula: "16129448",
    photo_url: `${BASE}/dayany-dayerlin-sanchez.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "00000000000",
    contact_relation: "Familiar",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-02",
    name: "Alejandro Wladimir Landaeta Mejías",
    age: null,
    gender: "M",
    last_location: "Edificio Bello Horizonte, Catia La Mar",
    latitude: 10.6,
    longitude: -66.95,
    description: "Desaparecido tras el terremoto del 24 de junio.",
    cedula: null,
    photo_url: `${BASE}/alejandro-landaeta.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "04243696841",
    contact_relation: "Familiar",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-03",
    name: "Paola Briceño",
    age: null,
    gender: "F",
    last_location: "Catia La Mar, Edificio Malecón, cerca del Club de Yates de La Guaira",
    latitude: 10.6,
    longitude: -66.95,
    description: null,
    cedula: null,
    photo_url: `${BASE}/paola-briceno.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "04141464092",
    contact_relation: "Familiar",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-05",
    name: "Clementina Segovia",
    age: null,
    gender: "F",
    last_location: "Edificio Costa Brava, Los Corales, La Guaira",
    latitude: 10.59,
    longitude: -66.92,
    description: "Desaparecida tras terremoto en Venezuela, 24 de junio.",
    cedula: "V-28155685",
    photo_url: `${BASE}/clementina-segovia.jpg`,
    status: "missing",
    contact_name: "Familiar",
    contact_whatsapp: "04243420415",
    contact_relation: "Familiar",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-06",
    name: "Ian Lambert",
    age: null,
    gender: "M",
    last_location: "La Guaira, Los Corales",
    latitude: 10.59,
    longitude: -66.92,
    description: null,
    cedula: "V-30225544",
    photo_url: `${BASE}/ian-lambert.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "04127240400",
    contact_relation: "Amigos",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-07",
    name: "Aaron Isaac Villalta",
    age: 8,
    gender: "M",
    last_location: "Pariata, La Guaira — Emergencia pediátrica Hospital Pérez Carreño",
    latitude: 10.58,
    longitude: -66.94,
    description: "Traído por Ven 911. SIN FAMILIAR. Se busca a su familia.",
    cedula: null,
    photo_url: `${BASE}/aaron-villalta.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "00000000000",
    contact_relation: "Hospital",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-08",
    name: "Alonso Cabrera",
    age: 6,
    gender: "M",
    last_location: "Edificio Bahía Mar, Av. Principal La Costanera",
    latitude: 10.6,
    longitude: -66.93,
    description: "Sobrino desaparecido tras el terremoto.",
    cedula: null,
    photo_url: `${BASE}/alonso-cabrera.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "00000000000",
    contact_relation: "Tía",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-09",
    name: "Antonio Cabrera",
    age: null,
    gender: "M",
    last_location: "Edificio Bahía Mar, Av. Principal La Costanera",
    latitude: 10.601,
    longitude: -66.931,
    description: "Piloto. C.I. 2904181. Desaparecido tras el terremoto.",
    cedula: "2904181",
    photo_url: `${BASE}/antonio-cabrera-piloto.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "00000000000",
    contact_relation: "Tía",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-11",
    name: "Francisco Antonio Marcano Paruta",
    age: 66,
    gender: "M",
    last_location: "Carayaca, estado La Guaira",
    latitude: 10.62,
    longitude: -66.92,
    description: "Desaparecido desde el terremoto del 24 de junio por la tarde.",
    cedula: null,
    photo_url: `${BASE}/francisco-marcano.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "04248726631",
    contact_relation: "Familiares",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-12",
    name: "Yimvert Berroterán",
    age: 18,
    gender: "M",
    last_location: "Los Corales, La Guaira",
    latitude: 10.59,
    longitude: -66.92,
    description: "Altura 1.80 m, contextura atlética. Jugador de fútbol.",
    cedula: null,
    photo_url: `${BASE}/yimvert-berroteran.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "04141133786",
    contact_relation: "FVF / Familia",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-13",
    name: "Ana Solangel Prieto",
    age: 67,
    gender: "F",
    last_location: "Aeropuerto de Maiquetía, salida de emergencia (última vez 7:30 pm)",
    latitude: 10.6,
    longitude: -66.98,
    description: "Tiene número extranjero. Está sola en Caracas.",
    cedula: null,
    photo_url: `${BASE}/ana-solangel-prieto.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "04249050375",
    contact_relation: "Familiar",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-14",
    name: "Génesis Aguirre y Maximiliano Merentes",
    age: null,
    gender: "F",
    last_location: "La Guaira, Tanaguarenas",
    latitude: 10.58,
    longitude: -66.9,
    description: "Madre e hijo. Sin información desde el terremoto.",
    cedula: null,
    photo_url: `${BASE}/genesis-aguirre-maximiliano.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "04248875689",
    contact_relation: "Familiar",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-15",
    name: "Skarlent Rodríguez",
    age: null,
    gender: "F",
    last_location: "Catia La Mar, Av. La Atlántida, Calle 7, Quinta Anache",
    latitude: 10.6,
    longitude: -66.95,
    description: null,
    cedula: null,
    photo_url: `${BASE}/skarlent-rodriguez.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "04244567728",
    contact_relation: "Familiar",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
  {
    id: "seed-16",
    name: "Natalia Benezra",
    age: 22,
    gender: "F",
    last_location: "La Guaira, zona Playa Pantaleta",
    latitude: 10.6,
    longitude: -66.93,
    description: "Estaba en La Guaira cuando ocurrió el terremoto del 24 de junio.",
    cedula: null,
    photo_url: `${BASE}/natalia-benezra.jpg`,
    status: "missing",
    contact_name: null,
    contact_whatsapp: "00000000000",
    contact_relation: "Familiar",
    contact_info: null,
    created_at: "2025-06-24T18:00:00Z",
    updated_at: "2025-06-24T18:00:00Z",
  },
];
