import type { Person } from "@/types/person";

export const MOCK_PERSONS: Person[] = [
  {
    id: "1",
    name: "María González Pérez",
    age: 45,
    gender: "F",
    last_location: "Caracas, La California Norte",
    description: "Vestía blusa azul y pantalón negro. Lleva gafas.",
    cedula: "V-12345678",
    photo_url: null,
    status: "missing",
    contact_name: "Carlos González",
    contact_whatsapp: "+584121234567",
    contact_relation: "Hijo",
    contact_info: null,
    created_at: "2025-06-24T14:30:00Z",
    updated_at: "2025-06-24T14:30:00Z",
  },
  {
    id: "2",
    name: "José Antonio Ruiz",
    age: 32,
    gender: "M",
    last_location: "Valencia, Naguanagua",
    description: "Camiseta blanca, jeans. Tatuaje en el brazo derecho.",
    cedula: null,
    photo_url: null,
    status: "found",
    contact_name: "Ana Ruiz",
    contact_whatsapp: "+584149876543",
    contact_relation: "Esposa",
    contact_info: "Localizado en Hospital Central de Valencia. Estable.",
    created_at: "2025-06-24T10:15:00Z",
    updated_at: "2025-06-25T08:00:00Z",
  },
  {
    id: "3",
    name: "Carmen Elena Díaz",
    age: 67,
    gender: "F",
    last_location: "Maracay, Los Samanes",
    description: "Vestido floral, sandalias. Usa bastón.",
    cedula: "V-87654321",
    photo_url: null,
    status: "missing",
    contact_name: "Luis Díaz",
    contact_whatsapp: "+584167654321",
    contact_relation: "Hijo",
    contact_info: null,
    created_at: "2025-06-24T16:45:00Z",
    updated_at: "2025-06-24T16:45:00Z",
  },
  {
    id: "4",
    name: "Pedro Luis Mendoza",
    age: 28,
    gender: "M",
    last_location: "Barquisimeto, Centro",
    description: "Chaqueta negra, mochila roja.",
    cedula: null,
    photo_url: null,
    status: "found",
    contact_name: "Rosa Mendoza",
    contact_whatsapp: "+584241112233",
    contact_relation: "Madre",
    contact_info: "En refugio temporal del Gimnasio UPEL. Contactar al coordinador.",
    created_at: "2025-06-24T12:00:00Z",
    updated_at: "2025-06-25T06:30:00Z",
  },
];
